### DataScience Libraries
- scipy.org site for these libraries

#### Numpy Library
- Processing N-Dimensional arrays

In [7]:
import numpy as np

li = [1,4,6,'A']
a = np.array(li)
#type(a)
a
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
rn = np.random.randint(1,19,size=5)
rn

array([ 5, 17,  2,  2,  9])

In [22]:
m3 = np.random.randint(0,2,size = (3,3,3,3))
m3[2][2][2][2]
m3

1

In [28]:
m3.ndim
m3.size
m3.shape
m3.dtype
m3.itemsize


4

In [29]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [34]:
# Extract sub array/matrix from matrix
m = np.random.randint(0,2,size = (3,3))
m1 = m[:2,:2]
m1
#m

array([[1, 1],
       [1, 1]])

In [36]:
c = b.reshape(5,3)
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [37]:
#Scalar addition --> Adding scalar value to the matrix
d = c + 2
d

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [40]:
s = np.ones((2,2))
s

array([[1., 1.],
       [1., 1.]])

### Pandas

Use Cases

- Data Cleaning
- Data Transformation
- Data Analysis

Notations

- Series
- Data Frames

In [3]:
import pandas as pd

internal1 = {'s1':21,'s2':18,'s3':24}

internal1 = pd.Series(internal1)

internal2 = {'s1':21,'s2':18,'s3':22}

internal2 = pd.Series(internal2)

internal2

s1    21
s2    18
s3    22
dtype: int64

In [9]:
final = {'internal1':internal1,'internal2':internal2}

final = pd.DataFrame(final)

final

final['internal1']

final.values[2]

#final.coulmn

array([24, 22], dtype=int64)

In [13]:
for row in final.values:
    print('Internal1 - ',row[0],'Internal2-',row[1])

Internal1 -  21 Internal2- 21
Internal1 -  18 Internal2- 18
Internal1 -  24 Internal2- 22


In [14]:
final

internal1  internal2
s1         21         21
s2         18         18
s3         24         22

In [15]:
final.loc['s4'] = [23,25]
final

internal1  internal2
s1         21         21
s2         18         18
s3         24         22
s4         23         25

In [16]:
final.values[2] = [21,19]
final

internal1  internal2
s1         21         21
s2         18         18
s3         21         19
s4         23         25

In [17]:
final.loc['s7'] = [22,20]
final

internal1  internal2
s1         21         21
s2         18         18
s3         21         19
s4         23         25
s7         22         20

In [18]:
final = final.drop('s7')
final

internal1  internal2
s1         21         21
s2         18         18
s3         21         19
s4         23         25